sudo: false
language: c
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
     - libgsl0-dev
before_install:
 - mkdir $HOME/usr
 - mkdir $HOME/usr/lib
 - pip install pytest-cov --install-option="--prefix=~/usr"
install:
 - make
 - make install INSTALL_DIR=$HOME/usr/lib
 - make pywrapper INSTALL_DIR=$HOME/usr/lib
script:
 - cd tests/
 - pytest -v test_basic.py --cov py
notifications:
  email:
    recipients:
      - jo.bovy@gmail.com
    on_success: change
    on_failure: change
