language: c
compiler:
  - clang
  - gcc
before_install:
 - sudo apt-get install libgsl0-dev
 - pip install pytest-cov
install:
 - make
 - make install
 - make pywrapper
script:
 - cd tests/
 - pytest -v test_basic.py --cov py
notifications:
  email:
    recipients:
      - jo.bovy@gmail.com
    on_success: change
    on_failure: change
