language: c
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
     - libgsl0-dev
before_install:
 - sudo pip install pytest-cov
install:
 - make
 - sudo make install
 - make pywrapper
script:
 - cd tests/
 - pytest -v test_basic.py --cov py
notifications:
  email:
    recipients:
      - jo.bovy@gmail.com
    on_success: change
    on_failure: change
